language: node_js
node_js:
  - "node"
  - "8"
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn test:coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
