export const REQUESTED_ITEMS = 'REQUESTED_ITEMS';
export const FETCHING_ITEMS = 'FETCHING_ITEMS';
export const FETCHED_ADS_SUCCESS = 'FETCHED_ADS_SUCCESS';
export const INCREASE_PAGE = 'INCREASE_PAGE';
